# Generated by Django 2.0.3 on 2025-08-02 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('dt_craiacao', models.DateTimeField(auto_now_add=True)),
                ('descricao', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
